version: '3.8'

services:
  web:
    build: .
    container_name: php_web
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html
    environment:
      - DB_HOST=host.docker.internal
